alert("SELECT YOUR FAVORITE ARTISTS \n TO PLAY THE SONG🎶");var musicArtists={ar:["./Music/AR/ar (1).mp3","./Music/AR/ar (2).mp3","./Music/AR/ar (3).mp3","./Music/AR/ar (4).mp3","./Music/AR/ar (5).mp3","./Music/AR/ar (6).mp3","./Music/AR/ar (7).mp3","./Music/AR/ar (8).mp3","./Music/AR/ar (9).mp3","./Music/AR/ar (10).mp3","./Music/AR/ar (11).mp3"],u1:["./Music/yuvan/u1 (1).mp3","./Music/yuvan/u1 (2).mp3","./Music/yuvan/u1 (3).mp3","./Music/yuvan/u1 (4).mp3","./Music/yuvan/u1 (5).mp3","./Music/yuvan/u1 (6).mp3","./Music/yuvan/u1 (7).mp3","./Music/yuvan/u1 (8).mp3","./Music/yuvan/u1 (9).mp3","./Music/yuvan/u1 (10).mp3","./Music/yuvan/u1 (11).mp3"],ani:["./Music/aniruth/aniruth (1).mp3","./Music/aniruth/aniruth (2).mp3","./Music/aniruth/aniruth (3).mp3","./Music/aniruth/aniruth (4).mp3","./Music/aniruth/aniruth (5).mp3","./Music/aniruth/aniruth (6).mp3","./Music/aniruth/aniruth (7).mp3","./Music/aniruth/aniruth (8).mp3","./Music/aniruth/aniruth (9).mp3","./Music/aniruth/aniruth (10).mp3","./Music/aniruth/aniruth (11).mp3"],sana:["./Music/sana/sana (1).mp3","./Music/sana/sana (2).mp3","./Music/sana/sana (3).mp3","./Music/sana/sana (4).mp3","./Music/sana/sana (5).mp3","./Music/sana/sana (6).mp3","./Music/sana/sana (7).mp3","./Music/sana/sana (8).mp3","./Music/sana/sana (9).mp3","./Music/sana/sana (10).mp3","./Music/sana/sana (11).mp3"],gv:["./Music/gv/gv (1).mp3","./Music/gv/gv (2).mp3","./Music/gv/gv (3).mp3","./Music/gv/gv (4).mp3","./Music/gv/gv (5).mp3","./Music/gv/gv (6).mp3","./Music/gv/gv (7).mp3","./Music/gv/gv (8).mp3","./Music/gv/gv (9).mp3","./Music/gv/gv (10).mp3","./Music/gv/gv (11).mp3"],mames:["./Music/mames/mames (1).mp3","./Music/mames/mames (2).mp3","./Music/mames/mames (3).mp3","./Music/mames/mames (4).mp3","./Music/mames/mames (5).mp3","./Music/mames/mames (6).mp3","./Music/mames/mames (7).mp3","./Music/mames/mames (8).mp3","./Music/mames/mames (9).mp3","./Music/mames/mames (10).mp3","./Music/mames/mames (11).mp3"],hiphop:["./Music/hiphop/hiphop (1).mp3","./Music/hiphop/hiphop (2).mp3","./Music/hiphop/hiphop (3).mp3","./Music/hiphop/hiphop (4).mp3","./Music/hiphop/hiphop (5).mp3","./Music/hiphop/hiphop (6).mp3","./Music/hiphop/hiphop (7).mp3","./Music/hiphop/hiphop (8).mp3","./Music/hiphop/hiphop (9).mp3","./Music/hiphop/hiphop (10).mp3","./Music/hiphop/hiphop (11).mp3"]};var numberOfButtons=document.querySelectorAll("button").length;var currentAudio=null;var curentBorder=null;for(i=0;i<numberOfButtons;i++){document.querySelectorAll("button")[i].addEventListener("click",function(){if(curentBorder!==null){for(n=0;n<numberOfButtons;n++){document.querySelectorAll("button")[n].style.border="none"}}
curentBorder=this.style.border="5px solid white"})}
document.querySelector(".ar").addEventListener("click",function(){if(currentAudio!==null){currentAudio.pause();currentAudio.currentTime=0}
var a=Math.floor(Math.random()*musicArtists.ar.length);var song=musicArtists.ar[a];currentAudio=new Audio(song);currentAudio.play()});document.querySelector(".u1").addEventListener("click",function(){if(currentAudio!==null){currentAudio.pause();currentAudio.currentTime=0}
var a=Math.floor(Math.random()*musicArtists.u1.length);var song=musicArtists.u1[a];currentAudio=new Audio(song);currentAudio.play()});document.querySelector(".ani").addEventListener("click",function(){if(currentAudio!==null){currentAudio.pause();currentAudio.currentTime=0}
var a=Math.floor(Math.random()*musicArtists.ani.length);var song=musicArtists.ani[a];currentAudio=new Audio(song);currentAudio.play()});document.querySelector(".sana").addEventListener("click",function(){if(currentAudio!==null){currentAudio.pause();currentAudio.currentTime=0}
var a=Math.floor(Math.random()*musicArtists.sana.length);var song=musicArtists.sana[a];currentAudio=new Audio(song);currentAudio.play()});document.querySelector(".gv").addEventListener("click",function(){if(currentAudio!==null){currentAudio.pause();currentAudio.currentTime=0}
var a=Math.floor(Math.random()*musicArtists.gv.length);var song=musicArtists.gv[a];currentAudio=new Audio(song);currentAudio.play()});document.querySelector(".mames").addEventListener("click",function(){if(currentAudio!==null){currentAudio.pause();currentAudio.currentTime=0}
var a=Math.floor(Math.random()*musicArtists.mames.length);var song=musicArtists.mames[a];currentAudio=new Audio(song);currentAudio.play()});document.querySelector(".hiphop").addEventListener("click",function(){if(currentAudio!==null){currentAudio.pause();currentAudio.currentTime=0}
var a=Math.floor(Math.random()*musicArtists.hiphop.length);var song=musicArtists.hiphop[a];currentAudio=new Audio(song);currentAudio.play()})